config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :enderecos
  resources :pessoas
  resources :unidades
  resources :torres
  resources :blocos
  resources :condominios

end

app/models/endereco.rb
class Endereco < ActiveRecord::Base

  belongs_to :pessoa

end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:tipo_logradouro, :logradouro, :numero, :complemento, :cep)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_for(@endereco) do |f| %>
  <% if @endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% @endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_logradouro %><br>
    <%= f.text_field :tipo_logradouro %>
  </div>
  <div class="field">
    <%= f.label :logradouro %><br>
    <%= f.text_field :logradouro %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :complemento %><br>
    <%= f.text_field :complemento %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form' %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo logradouro</th>
      <th>Logradouro</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Cep</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.tipo_logradouro %></td>
        <td><%= endereco.logradouro %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.complemento %></td>
        <td><%= endereco.cep %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form' %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo logradouro:</strong>
  <%= @endereco.tipo_logradouro %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @endereco.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @endereco.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @endereco.complemento %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @endereco.cep %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>