config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :enderecos
  resources :pessoas
  resources :unidades
  resources :torres
  resources :blocos
  resources :condominios

end

app/models/bloco.rb
class Bloco < ActiveRecord::Base

  belongs_to :condominio
  has_many :torres, :dependent => :destroy

end

app/controllers/blocos_controller.rb
class BlocosController < ApplicationController
  before_action :set_bloco, only: [:show, :edit, :update, :destroy]

  # GET /blocos
  # GET /blocos.json
  def index
    @q = Bloco.ransack(params[:q])
    @blocos = @q.result.paginate(:per_page => 10, :page => params[:page])
  end

  # GET /blocos/1
  # GET /blocos/1.json
  def show
  end

  # GET /blocos/new
  def new
    @bloco = Bloco.new
  end

  # GET /blocos/1/edit
  def edit
  end

  # POST /blocos
  # POST /blocos.json
  def create
    @bloco = Bloco.new(bloco_params)

    respond_to do |format|
      if @bloco.save
        format.html { redirect_to @bloco, notice: 'Bloco was successfully created.' }
        format.json { render :show, status: :created, location: @bloco }
      else
        format.html { render :new }
        format.json { render json: @bloco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocos/1
  # PATCH/PUT /blocos/1.json
  def update
    respond_to do |format|
      if @bloco.update(bloco_params)
        format.html { redirect_to @bloco, notice: 'Bloco was successfully updated.' }
        format.json { render :show, status: :ok, location: @bloco }
      else
        format.html { render :edit }
        format.json { render json: @bloco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocos/1
  # DELETE /blocos/1.json
  def destroy
    @bloco.destroy
    respond_to do |format|
      format.html { redirect_to blocos_url, notice: 'Bloco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bloco
      @bloco = Bloco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bloco_params
      params.require(:bloco).permit(:descricao, :sigla, :condominio_id)
    end
end

app/helpers/blocos_helper.rb
module BlocosHelper
end

app/views/blocos/_form.html.erb
<%= bootstrap_form_for(@bloco, layout: :horizontal, label_col: "col-sm-0", control_col: "col-sm-8") do |f| %>
<%= f.alert_message "Por favor, verifique os campos abaixo.", error_summary: false %>
  <%= f.label 'Condomínio' %>
  <%= f.collection_select :condominio_id, Condominio.all, :id, :nome, skip_label: true  %>
  <%= f.label :descricao %>
  <%= f.text_field :descricao, skip_label: true %>
  <%= f.label :sigla %>
  <%= f.text_field :sigla, skip_label: true %>
  <%= f.form_group do %>
    <%= f.submit 'Submeter Formulário', class: "btn btn-primary"%>
    <%= link_to t('.back', :default => t("helpers.links.back")),
              blocos_path, :class => 'btn btn-default'  %>
  <% end %>
<% end %>

app/views/blocos/edit.html.erb
<%- model_class = Bloco -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blocos/index.html.erb
<%- model_class = Bloco -%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
  </div>
  <div class="panel-body">
    <%= search_form_for @q do |f| %>
      <%= f.label 'Consultar' %>
      <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <div class="input-group">
            <%= f.search_field :descricao_cont, class: "form-control" %>
            <spam class="input-group-btn">
              <%= f.submit 'Buscar', class: "btn btn-default" %>
            </spam>
          </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <%= link_to t('.new', :default => t("helpers.links.new")),
            new_bloco_path,
            :class => 'btn btn-primary pull-right' %>
        </div>
      </div>
    <% end %>
    </br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:descricao) %></th>
          <th><%= model_class.human_attribute_name(:sigla) %></th>
          <th><%= model_class.human_attribute_name(:condominio_id) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th colspan=4 style="text-align: center;"><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @blocos.each do |bloco| %>
          <tr>
            <td><%= link_to bloco.id, bloco_path(bloco) %></td>
            <td><%= bloco.descricao %></td>
            <td><%= bloco.sigla %></td>
            <td><%= bloco.condominio.nome %></td>
            <td><%=l bloco.created_at, :format => :short %></td>
            <td style="text-align: center;">
              <%= link_to '', bloco_path(bloco), :class => 'glyphicon glyphicon-search' %>
            </td>
            <td style="text-align: center;">
              <%= link_to '', edit_bloco_path(bloco), :class => 'glyphicon glyphicon-pencil' %>
            </td>
            <td style="text-align: center;">
              <%= link_to '', bloco_path(bloco),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'glyphicon glyphicon-trash' %>
            </td>
            <td style="text-align: center;">
              <%= link_to '', new_torre_path, :class => 'glyphicon glyphicon-plus' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @condominios, :previous_label => t("Anterior"), :next_label => t("Próximo"), renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/blocos/new.html.erb
<%- model_class = Bloco -%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
  </div>
  <div class="panel-body">
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/blocos/show.html.erb
<%- model_class = Bloco -%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
  </div>
  <div class="panel-body">

    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:condominio_id) %>:</strong></dt>
      <dd><%= @bloco.condominio.nome %></dd>
      <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
      <dd><%= @bloco.descricao %></dd>
      <dt><strong><%= model_class.human_attribute_name(:sigla) %>:</strong></dt>
      <dd><%= @bloco.sigla %></dd>
    </dl>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                  blocos_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_bloco_path(@bloco), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  bloco_path(@bloco),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  </div>
</div>